### ISSUE TITLE
Exception Undefined array key "start"

### ISSUE THREAD

**Issue by hvanrees** [EmicoEcommerce/Magento2Tweakwise#105]
Issue Brief
--
Error on missing array key

Environment
--
* PHP Version: (8.1)
* Magento Version: 2.4.6
* Tweakwise Version: 5.7.0
* Magento Deploy Mode: (development)

Steps to reproduce
--
1. Install Magento from `master` branch.
2. Open any page in store

Actual result
--
1. Exception #0 (Exception): Warning: Undefined array key "start" in /var/www/html/vendor/tweakwise/magento2-tweakwise/Model/Client/Timer.php on line 54

Expected result
Not an exception

**Comment by npluimers** [comment]
This error also occurs in the Timer.getTime function https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/Model/Client/Timer.php#L69

@ah-net could you also investigate/fix this? :)
