### ISSUE TITLE
XSS on category overview page

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#117]
XSS on the category overview page
--
XSS vulnerability could be used to steal customer data.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5, 2.4.6
* Tweakwise Version: 5.6.5, 5.7.3
* Tweakwise Export Version: 5.4.0
* Magento Deploy Mode: production

details shared with support

Actual result
--
Script executed on page visit

Expected result
--
no script execution

**Comment by ahuininga-orisha** [comment]
@vshatylo I can't seem to reproduce the issue. Can you check if it's not an theme issue? By checking if the problem also exists in the luma (or hyva) theme?

**Comment by vshatylo** [comment]
> @vshatylo I can't seem to reproduce the issue. Can you check if it's not an theme issue? By checking if the problem also exists in the luma (or hyva) theme?

please, try with param "product_list_order"
