### ISSUE TITLE
Broken swagger page

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#118]
Swagger page doesn't show allowed resources because of improper type declaration in PHP docs.
Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.6
* Tweakwise Version: 5.7.3
* Tweakwise Export Version: 5.4.0
* Magento Deploy Mode: developer
* 
Steps to reproduce
--
1. Install Magento from `master` branch.
2. visit swagger page. e.g.  https://www.example.com/swagger

Actual result
--
1. error shown "Failed to load API definition"

Expected result
--
allowed API endpoints are shown.

**Comment by ahuininga-orisha** [comment]
@vshatylo Can you give the error of which declarations are wrong? I've tried to reproduce the issue, but swagger isn't working for me at all. It isn't generating an json file at all and is giving no exceptions.

**Comment by vshatylo** [comment]
@ah-net 
error is next 
`The "array[]" class doesn't exist and the namespace must be specified. Verify and try again.`

problem in file https://github.com/EmicoEcommerce/Magento2AttributeLanding/blob/master/src/Api/Data/LandingPageInterface.php

line: 162

**Comment by ahuininga-orisha** [comment]
@vshatylo Fixed in 
https://github.com/EmicoEcommerce/Magento2AttributeLanding/commit/7d9c39f94223b9d4911b9d95d0fffefc0c59a6cf
