### ISSUE TITLE
Category filter doesn't take into account applied filter

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#120]
Usually, customers use a category tree in the filter bar.
Category tree works in some cases unexpectedly.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.6
* Tweakwise Version: 5.7.3
* Tweakwise Export Version: 5.4.0
* Magento Deploy Mode: production

Pre-Conditions
 - ajax filter is enabled
 - category added to filter template as a tree
 - URL Strategy: Query params

Steps to reproduce
--
1. visit the category overview page. e.g. https://example.con/category_path_url
2. apply one filter (not category). e.g. https://example.con/category_path_url?filter_name=filter_value
3. click on the category in the filter. 

Actual result
--
- filter from step 2 is not applied
- customers are confused by the number of matched products. Because in step 2, the category tree shows a number of matched products with the applied filter.

Expected result
--
List the expected results as a bullet list of expectations
- category tree filter takes into account applied filters.

**Comment by ahuininga-orisha** [comment]
@vshatylo The problem with this is that there is no guarantee that the applied filter exists in other categories (because you can change the filter template per category in TW). So the bug is (in my opinion) that the category shows the number of products with the matched filter. I'll discuss this internally beacause i think this may be an api issue.

**Comment by ahuininga-orisha** [comment]
@vshatylo I did some testing and it only seems to happen if the url strategy is query parameters. The filter does get added if you're using seo path slugs. I'll see if we can also make this work query parameters.
