### ISSUE TITLE
ajax filtering for category tree, attribute landing page

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#121]
Ajax filtering doesn't work consistently with category filters, or attribute landing page filters.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.6
* Tweakwise Version: 5.7.3
* Tweakwise Export Version:  5.4.0
* Magento Deploy Mode: production

Pre-conditions
- ajax filtering is enabled
- category tree is added to the filter template
- there are managed landing pages

Steps to reproduce
--
1. visit category page
2. click on the link in the category tree or filter that matches the landing page

Actual result
--
page fully refreshed

Expected result
--
content updated with ajax

**Comment by ahuininga-orisha** [comment]
@vshatylo I think that is by design for the category filter. To update the meta title etc with category information. I'll discuss this internally, but I'm not sure if it is something we should change.

**Comment by ahuininga-orisha** [comment]
@jansentjeu, could you share your thoughts on this?

When the category filter is applied, or when a filter link to an ALP is clicked with AJAX enabled, the page refreshes. I believe this is done to update the URL, metadata, and other content.

Given that this action essentially loads another page rather than just altering the product selection, I don't see an reason to change this behavior.

**Comment by jansentjeu** [comment]
> @jansentjeu, could you share your thoughts on this?
> 
> When the category filter is applied, or when a filter link to an ALP is clicked with AJAX enabled, the page refreshes. I believe this is done to update the URL, metadata, and other content.
> 
> Given that this action essentially loads another page rather than just altering the product selection, I don't see an reason to change this behavior.

@ah-net Yes indeed. This is how it works as it was designed and it should remain that way in the module. If this URL and other elements are no longer changed, page measurements from GA will no longer be updated, etc.

**Comment by ahuininga-orisha** [comment]
@vshatylo Since this is by design, we are not going to change this.
