### ISSUE TITLE
brand pages

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#122]
There are many customers that are using brand pages. 
There is an option to do it via landing pages but it's time-consuming and there is no automation for it.
Will be nice to have such an option out of the box with tweakwise extension.

**Comment by ahuininga-orisha** [comment]
@vshatylo Good idea. We've added this to our backlog. Not sure if/when this is going to be implemented. The idea is to generate landing pages based on brands/categories/etc.

I'll close this issue for now and if we will add this feature you can see it in the release notes.
