### ISSUE TITLE
Introduce some kind of automated linting (and fixing) to improve code quality

### ISSUE THREAD

**Issue by Swahjak** [EmicoEcommerce/Magento2Tweakwise#134]
Issue Brief
--
In example; the following class has about 24 use statements, while only 2 are actually used. This is probably due to some refactoring at a point in time, but from a quality perspective this doesn't give me a lot of confidence. Not by any means saying that it lacks quality, I haven't gone into the code enough to say anything about it. But if such a simple task, that can be easily automated, is neglected it doesn't make me (the customer) very confident about the overall quality.

Also; adding code quality tools and linters makes it much easier to contribute.

Environment
--
-

Steps to reproduce
--
-

Actual result
--
-
Expected result
--
-

**Comment by ahuininga-orisha** [comment]
Good idea. I've added this this to our backlog. The plan is to add an phpcs linter to our CI pipeline. I'll close this issue for now since it's on our backlog.

**Comment by Swahjak** [comment]
I would prefer for this issue to stay open, since it is on you backlog but hasn't actually been resolved. That way I can be notified, if and, when this issue has actually been resolved without having to monitor release notes.

**Comment by ahuininga-orisha** [comment]
@Swahjak I'll understand. I'll reopen the issue for now.

**Comment by ahuininga-orisha** [comment]
@Swahjak We now have an linter in our workflow. In the next release there will be changes to improve the code quality.
