### ISSUE TITLE
Personal Merchandising

### ISSUE THREAD

**Issue by vacla** [EmicoEcommerce/Magento2Tweakwise#148]
Issue Brief
--
The page is not being refreshed correctly and you can't use the toolbar.

If you enable form filter, there is no "on change" used, see:
https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/view/frontend/web/js/navigation-form.js#L78-L84

Only change is being called in these two spots:
https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/view/frontend/web/js/toolbar.js#L74
https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/view/frontend/web/js/pm-page-reload.js#L35

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p5
* Tweakwise Version: v5.8.1
* Tweakwise Export Version: v6.0.0
* Magento Deploy Mode: production/development
* Third party modules:

Steps to reproduce
--
1. Configure personal merchandising, enable ajax and filter form and use url strategy query param.
2. Go to a category
3. Click for going to the next page

Actual result
--
After step 2, there is no ajax request sent
After step 3, same thing

Expected result
--
ajax requests being sent

**Comment by ahuininga-orisha** [comment]
@vacla

2) After you go to the category page, no ajax request for personal merchandising is sent? I'll look into this futher.
3) The pagination works if you click on p=3 and then click on show items. However this doesn't seem to be very user friendly. I'll discuss this internally and see if we can change this.

**Comment by vacla** [comment]
@ah-net Is there any update on this issue?
