### ISSUE TITLE
Hidden filters doesn't work with AJax

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#150]
Issue Brief
--
Tweakwise allows setting the filter as "hidden|not to show" in the filter template but filtering by it is still workable. 
Such filters could be used for marketing to point users to special products.

Environment
--
PHP Version: 8.1
Magento Version: 2.4.6
Tweakwise Version: 5.7.3
Tweakwise Export Version: 5.4.0
Magento Deploy Mode: production

Pre-conditions

- ajax filtering is enabled
- configure filter template with hidden filter
- URL strategy: Query params
![Screenshot from 2024-02-07 10-48-23](https://github.com/EmicoEcommerce/Magento2Tweakwise/assets/43958431/037dfd71-3b21-433b-8a6f-873b28f1d92a)

Steps to reproduce
--
1. visit a category with an applied "hidden" filter. e.g. /category_path/?test_hidden=test
2. try to navigate to the second page, or change sorting, or add one more filter

Actual result
--
- hidden filter is not applied to the result

Expected result
--
- the results should be the same: despite of whether it's rendered by AJax or not.

**Comment by ahuininga-orisha** [comment]
@vshatylo The problem with this is that magento doesn't know which filters exists in TW and which filters are hidden filters.

Do you have an suggestion how to determine which filter should be applied and which not?

**Comment by vshatylo** [comment]
i was thinking about 2 ways 
- apply all filters that are in the URL when building Ajax requests. in this case, hidden param are not lost during Ajax filtering. 
Tweakwise anyway ignores filters that are not in the filter template.
- sync filter templates with Magento. Tweakwise allows us to get information about filter templates by API. 
Then we could determine which filters are hidden.

**Comment by ahuininga-orisha** [comment]
@vshatylo 

Solution 1 has the problem that you can't detect which filter you just deactivated if you use all url params. Than the deactivated filter just gets activated again.

Solution 2 could work. But filter templates can differ for categories. You can determine if an filter is an hidden filter, but it can be an hidden filter in an different filter template than the current category.

I'll discuss this internally and see if we can come up with an solution for this.

**Comment by ahuininga-orisha** [comment]
@vshatylo Is there an reason that you don't use the ALP module for this? You can enable hidden filters there, and an ALP works on an specific url

**Comment by vshatylo** [comment]
> @vshatylo Is there an reason that you don't use the ALP module for this? You can enable hidden filters there, and an ALP works on an specific url

**Expected result**
the results should be the same: despite of whether it's rendered by AJax or not.


now it works differently

 - you visit category with hidden filter 
 - you see one collection of products 
 - you navigate to the second page 
 - you see totally new  collection of products

**Comment by ahuininga-orisha** [comment]
@vshatylo Then the bug is (in my opinion) that you can set an hidden filter via the url (?hidden_filter=test).

So if you want to use an hidden filter, you can use an ALP page. And otherwise if the hidden filter is in the url. It should not change the product selection on the first page.

**Comment by ahuininga-orisha** [comment]
To fix this issue you have two options

> 
> * apply all filters that are in the URL when building Ajax requests. in this case, hidden param are not lost during Ajax filtering.
>   Tweakwise anyway ignores filters that are not in the filter template.
> * sync filter templates with Magento. Tweakwise allows us to get information about filter templates by API.
>   Then we could determine which filters are hidden.

But both options have problems

> 
> Solution 1 has the problem that you can't detect which filter you just deactivated if you use all url params. Than the deactivated filter just gets activated again.
> 
> Solution 2 could work. But filter templates can differ for categories. You can determine if an filter is an hidden filter, but it can be an hidden filter in an different filter template than the current category. 
> 

@jansentjeu Can I get your input on this? I don't think both solutions are good options to fix this problem.

**Comment by ahuininga-orisha** [comment]
@vshatylo There are currently no plans to fix this. This is due to the low impact of this issue, and not having good solution for this problem. This problem only occurs if you know the values for an hidden filter, and add them to the url yourself.
