### ISSUE TITLE
Autocomplete search instant result

### ISSUE THREAD

**Issue by CreamDevelopment** [EmicoEcommerce/Magento2Tweakwise#25]
At the moment the autocomplete of the search is done via Magento logic. This causes delay in retrieving the result. The data you want to show in the autocomplete window is available in Tweakwise. It would be nice if there was an option where you can choose to retrieve the data directly from Tweakwise without the intervention of Magento. Since autocomplete results are not cached in Magento, this makes a significant difference when this comes directly from Tweakwise and can be handled completely via the frontend.

**Comment by ahuininga-orisha** [comment]
Good idea, I've added this to our backlog
