### ISSUE TITLE
Question: how do you get featured products by id/name

### ISSUE THREAD

**Issue by edwinbos** [EmicoEcommerce/Magento2Tweakwise#27]
How do you get featured products by id/name from the following list in Tweakwise in Magento 2?

![tweakwise](https://user-images.githubusercontent.com/1267356/207098549-5b47c208-9e76-4d69-bc7a-f78f82916595.png)

It's not clear from the documentation, readme or in the code. You can choose a default featured "default featured product template", but it's not clear where the products are coming from.

Maybe a good idea to put this information in the documentation.

**Comment by ahuininga-orisha** [comment]
@edwinbos Edited

I just read you're question again, and i think i misunderstood your question. Which products are shown is determined on the tweakwise side. The only thing you can select on the magento side is, which template or group code for featured products you show on which locations. (you can show diffrent featured products on different categories).
https://support.tweakwise.com/nl/cat/magento-recommendations/1216

But to determine which products are shown, see:
https://support.tweakwise.com/nl/cat/uitgelichte-producten/89

And if you use group codes, see. Group codes work the same for featured products as for up/crossell.
https://support.tweakwise.com/nl/cat/up-cross-sell/91
