### ISSUE TITLE
Empty product collections returned by ElasticSearch - Wrong collectionProvider used, when fixed, filtering and toolbar not working

### ISSUE THREAD

**Issue by jspoe** [EmicoEcommerce/Magento2Tweakwise#51]
Issue Brief
--
Sometimes, no product collection is being returned by Tweakwise. Because of a republish or the API that is temporarily unavailable.
If this happens, the logic should fallback on the default Magento collection, but it returns an empty collection because of an error in ElasticSearch. Biggest problem is that empty product pages are cached too, so unless you flush the cache, customers will see an empty product page.

Prerequisties:
- Simulate no collection returned by Tweakwise (which sometimes happens), by adding the following to at the beginning of the function:
`vendor/tweakwise/magento2-tweakwise/Model/Catalog/Layer/ItemCollectionProvider.php :: getCollection`

```
$this->config->setTweakwiseExceptionThrown(); //Mandatory, but makes sure the default Magento filtering is being used
return $this->originalProvider->getCollection($category);
```

- Go to a Product List Page, containing Layered Navigation

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p2 Commerce
* Tweakwise Version: 5.3.3
* Tweakwise Export Version: 5.2.0
* ElasticSearch7
* Magento Deploy Mode: production, development, doesn't matter
* Third party modules:

Expected result:
- Working product collection, filters, toolbar

Actual result:
- Empty product collection, no product list. Biggest problem is that empty product pages are cached too, so unless you flush the cache, customers will see an empty product page.

---

Little information I accuired from the investigation:
If the current logic fallback, calls the collection of the originalProvider, it still retrieves the products from ElasticSearch.
However, an error occurs fetching the products from ElasticSearch because the sortOrder is empty (no field and no direction are given). 

`{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:107] [field_sort] failed to parse field [order]"}],"type":"x_content_parse_exception","reason":"[1:107] [field_sort] failed to parse field [order]","caused_by":{"type":"illegal_argument_exception","reason":"No enum constant org.elasticsearch.search.sort.SortOrder."}},"status":400}`

This sortOrder is normally given by a collectionProvider of ElasticSearch (a virtualType: elasticsearchLayerCategoryItemCollectionProvider)
But Magento\CatalogSearch\Model\Layer\Category\ItemCollectionProvider is used by Tweakwise instead.

If you change the following part to ElasticSearch, you do get a collection (which also is the correct collection), but filtering and the toolbar are broken (meaning: collection is not filtered, nor pagination does work).

```
    <!-- Tweakwise virtual collection provider types used in overrides of magento collection providers -->
    <virtualType name="Tweakwise\Magento2Tweakwise\Model\Catalog\Layer\ItemCollectionProvider\Category" type="Tweakwise\Magento2Tweakwise\Model\Catalog\Layer\ItemCollectionProvider">
        <arguments>
            <argument name="originalProvider" xsi:type="object">elasticsearchLayerCategoryItemCollectionProvider</argument>
            <argument name="navigationContext" xsi:type="object">Tweakwise\Magento2Tweakwise\Model\Catalog\Layer\NavigationContext\Category</argument>
        </arguments>
    </virtualType>
```

**Comment by ahuininga-orisha** [comment]
@jspoe Thx for submitting this issue. We will rewrite the fallback for when tweakwise doesn't give an valid response.

However, tweakwise should always be available when doing an republish. If this issue occurs then you can contact support@tweakwise.com with the steps needed to reproduce it, because it should not happen. And we need to investigate this futher on the api side.

**Comment by jspoe** [comment]
Hi @ah-net ,

Thank you for looking into this! I was not entirely sure about the republish either, but I suspected it because it happens quite a lot for the customer, but might just be a connection / API issue too. I'll see if I can dig something from the log about how often this happens. As far as I know, we have no reproduction scenario other than described (locally forcing a collection from Magento), it happens randomly, I think at invalidated cached categories, so that is why I suspected these 2 causes.

**Comment by ahuininga-orisha** [comment]
@jspoe I've made an pull request for this. Could you test if it works for you?

**Comment by jspoe** [comment]
Hi @ah-net Great, thank you for the PR! I'll see if I can test it in the upcoming week and will get back to you with the results.

**Comment by jspoe** [comment]
Hi @ah-net 

I've tested this functionality and after some local changes (custom code that did not take into account that there could be a fallback), this all seems to work well!

My testscenario was as follow:
- I added an entry to my hostfile for gateway.tweakwisenavigator.net to mimic an empty response and/or unavailable server
- Loaded a PLP
- Tested if filtering was working
- Tested if pagination was working
- Tested if sorting was working

A few notes for people who experience this in the future:
- If this happens, filter and sorting appearance might differ (which is a logic outcome, considering it is a fallback)
- ElasticSearch has to be indexed (ofcourse)

**Comment by ahuininga-orisha** [comment]
This code is reverted in the latest release. It has issues with all items shown in all categories.

**Comment by YouriGuapa** [comment]
Dear Tweakwise, ah-net,

Five months ago, my colleague Johan Spoelstra submitted the above ticket on behalf of our mutual client, United Retail. We greatly appreciate all the assistance and effort you have put into resolving the issue over the past months. However, the fact that the problem has been outstanding for so long is beginning to have operational and revenue implications for United Retail.

We would like to request that the above-mentioned issue be readdressed, and that a suitable solution be found by the first week of October.

I look forward to hearing from you.

Kind regards,

Youri Schepel
Managing Director, Guapa B.V.

**Comment by ahuininga-orisha** [comment]
@YouriGuapa 

We've added the solution for this in the latest release (v5.7.0)
