### ISSUE TITLE
Saving visual swatches failed

### ISSUE THREAD

**Issue by vacla** [EmicoEcommerce/Magento2Tweakwise#54]
Issue Brief
--
Cannot save visual swatch attribute due to attribute source being set by tweakwise first before Magento swatches save plugin can modify the data after saving.
Disabling following observer, fixes the issue: https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/etc/events.xml#L8-L13
This is due that the store id for the following source would be null and returns 1 (this is not default store id) and it will be used in following calls by magento and likewise in magento swatches module, when disabling the observer magento will set store id 0 when in the source then it will be also be getting store id 0 instead of 1 when it is enabled.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p1
* Tweakwise Version: v5.0.9
* Tweakwise Export Version: v5.0.3
* Magento Deploy Mode: production & development
* Third party modules:

Steps to reproduce
--
1. Install Magento from `master` branch.
2. Configure an visual swatch attribute like: ![image](https://user-images.githubusercontent.com/10290022/234626175-a4f44df3-a6da-4c83-84b0-189d8efde4b8.png)
3. Save

Actual result
--
1. Error message appears: "Warning: Undefined array key 5 in /app/xxxxx/vendor/magento/module-swatches/Model/Plugin/EavAttribute.php on line 241".

Expected result
--
List the expected results as a bullet list of expectations
- [ ] Be able to save attribute options.

**Comment by ahuininga-orisha** [comment]
@vacla 

It seems it only happens with integer values for the admin column. If you add an text value in that column it seems to work. I'l see if I can find an solution for this.

**Comment by vacla** [comment]
@ah-net I just tried your fix using dev branch using composer, and it seems to work.
