### ISSUE TITLE
Filters no longer combining after update to v5.4.4

### ISSUE THREAD

**Issue by npluimers** [EmicoEcommerce/Magento2Tweakwise#77]
Issue Brief
--
Hello, we recently updated the Tweakwise extension in our store to the latest version, however, while doing this we noticed an issue that's causing filters to no longer be combined

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p2
* Tweakwise Version: 5.4.4 (and higher)
* Magento Deploy Mode: production

Steps to reproduce
--
1. Install affected version
2. Visit page with navigation
3. Enable one filter from one attribute
4. Try to also select another filter from another attribute

Actual result
--
1. Only the most recently selected filter is selected
2. The url turns into (domain)//category/?filter=1

Expected result
--
List the expected results as a bullet list of expectations
- [ ] The selected filter is added to the list of filters
- [ ] URL becomes (domain)/category?filter=1&other_filter=2

**Comment by maxivol** [comment]
We have the  same issue in version 5.4.0
PHP Version 8.1
Magento ver. 2.4.6-p1
