### ISSUE TITLE
filters on PLP breaks addtocompare functionality 

### ISSUE THREAD

**Issue by Hayyan-Ebrahem** [EmicoEcommerce/Magento2Tweakwise#78]
Issue Brief
--
When filtering products on PLP and then add a product to comparelist it redirects to "tweakwise/ajax/navigation/XXX" instead of redirecting to the page from which the current request   was initiated "category page", For now removing "uenc" from addtocompare datapost will resolve it but not for long term.

Environment
--
* PHP Version: (7.4|8.1|8.1)
* Magento Version: 2.4.5-p2
* Tweakwise Version: 5.5.2

**Comment by dz-optimizers** [comment]
@Hayyan-Ebrahem 
This seems like a problem in Magento, but we found a solution. You can add $url as a parameter in vendor/magento/framework/Data/Helper/PostHelper.php on line 44 in the getPostData function like below:
$data[\Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED] = $this->urlHelper->getEncodedUrl();
to >
$data[\Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED] = $this->urlHelper->getEncodedUrl($url);
Let us know if this fixes the problem for you.

**Comment by ahuininga-orisha** [comment]
Closed due to inactivity
