### ISSUE TITLE
Store Code in url removed after ajax response

### ISSUE THREAD

**Issue by kaplansin** [EmicoEcommerce/Magento2Tweakwise#79]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p3
* Tweakwise Version: 5.4.2
* Tweakwise Export Version:
* Magento Deploy Mode: (development)
* Third party modules:

Steps to reproduce
--
1.Enable store code in url. confifg path : web/url/use_store
2. Navigate to a category page [domain]/[storecode]/[categorykey]
3. After getting response from this ajax call.
[domain]/[storecode]/tweakwise/ajax/navigation/?__tw_ajax_type=category&__tw_object_id=[objectId]&__tw_original_url=[originalUrl]&__tw_hash=[hash]

Actual result
--
1- storecode in url will be removed
[domain]/[categorykey]

Expected result
--
if Store code in url is enabled (web/url/use_store) store code in url should remain as it is in any condition.

**Comment by Beagon** [comment]
I've got the exact same issue. This can be traced back to version 5.4.4. I've reverted to 5.4.3 on my instance.
