### ISSUE TITLE
Wrong url for parent category in category tree

### ISSUE THREAD

**Issue by vshatylo** [EmicoEcommerce/Magento2Tweakwise#81]
Issue Brief
--
Hello, we are using a category filter as a tree. 
When a child category is selected, we encounter an issue with the parent category URL.

Environment
--
* PHP Version: 8.1
* Magento Version: 2.4.5-p3
* Tweakwise Version: 5.5.1
* Tweakwise Export Version: 5.3.1
* Magento Deploy Mode: production

Steps to reproduce
--
1. Install Magento from `master` branch.
2. Export configurable product with multiple children and 2 configurable attributes to Tweakwise.
3. Configure category filter in Tweakwise "Display filter values" as "Tree"
4. Check the Magento child category overview page ( category level 3 or deeper)

Actual result
--
1. Parent category URL has the same URL as Child. Can't follow the parent category.

Expected result
--
- Parent category has the correct URL

**Comment by vshatylo** [comment]
bug in code 
https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/master/Model/Catalog/Layer/Filter/Item.php
in line 129
need to replace 
**$settings->getSelectionType()** 
with 
**$settings->getSource()**

**Comment by dz-optimizers** [comment]
@vshatylo is it still a problem in the latest version? Because we can not reproduce it. 
If so. Can you provide more information? Maybe a recording to show it. Also with the url in the recording.

**Comment by vshatylo** [comment]
@dz-optimizers 
bug looks next
![Screenshot from 2023-12-21 15-37-09](https://github.com/EmicoEcommerce/Magento2Tweakwise/assets/43958431/c8967134-52cc-4af0-bd52-cfccedfbcd3f)

I'm on the category page "KAMADO BARBECUES" and the link for parent category "Barbecues" has wrong link.

**Comment by ahuininga-orisha** [comment]
I'll take another look at this and see if we can reproduce the issue
