### ISSUE TITLE
Bugs in search.banner.phtml

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [EmicoEcommerce/Magento2Tweakwise#82]
#90 {main} {"exception":"[object] (Exception(code: 0): Warning: Undefined array key 0 in /var/domains/xxx/application/releases/251/var/view_preprocessed/pub/static/vendor/tweakwise/magento2-tweakwise/view/frontend/templates/searchbanner/search.banner.phtml on line 1 at /var/domains/xxx/application/releases/251/vendor/magento/framework/App/ErrorHandler.php:62)"} []
[2023-08-16T06:30:49.723462+00:00] main.CRITICAL: Exception: Warning: Undefined array key 0 in /var/domains/xxx/application/releases/251/var/view_preprocessed/pub/static/vendor/tweakwise/magento2-tweakwise/view/frontend/templates/searchbanner/search.banner.phtml on line 1 in /var/domains/xxx/application/releases/251/vendor/magento/framework/App/ErrorHandler.php:62

Error on search page because there is no check in file vendor/tweakwise/magento2-tweakwise/view/frontend/templates/searchbanner/search.banner.phtml on line 4 if $banners[0] key exists.

Also on line 9 attribute 'type' on anchor has syntax error:
is: 
`<a href="<?=$banner['clickurl'];?>" type=<?=$banner['clicktarget'];?>">`
should be:
`<a href="<?=$banner['clickurl'];?>" type="<?=$banner['clicktarget'];?>">`

**Comment by dz-optimizers** [comment]
I've fixed it in the above files instead of in search.banner because when there are no banners, it does'nt set unused php code and the unused view.

**Comment by ahuininga-orisha** [comment]
Closed with #96
