### ISSUE TITLE
Inconsistent product amount on catalog pages

### ISSUE THREAD

**Issue by HyperC** [EmicoEcommerce/Magento2Tweakwise#95]
Issue Brief
--
The amount of products displayed on catalog pages is not consistent per page. Product with 0 stock are being exported to Tweakwise and displayed in the feed on the Tweakwise side. In the Magento catalog however, the products aren't displayed. Out of stock products should not be exported to Tweakwise at all.

The 'Export out of stock combined product children' option is already set to 'No'.

**Comment by dz-optimizers** [comment]
@HyperC 
We have tested it and it's a timing issue. If the Magento setting in Stores > Configuration > Inventory > Stock Options > Display Out of Stock Products = No, the Tweakwise export will not export the product to Tweakwise if all color and size combinations/variants are out of stock. 
Once Tweakwise export has run again, the amount of products will be shown correct.
