### ISSUE TITLE
Feature request: Success logs only when debug is enabled.

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2Tweakwise#99]
https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/e7e3e5be0e917d4190ae96b94e625136e5b25ba1/Model/Client.php#L191

Ideally I would only like to see this log based on a debug configuration setting instead of always logging it.

**Comment by ahuininga-orisha** [comment]
@arnoudhgz You mean log based on if the debug log is enabled or not? I'll add this to our backlog. And close this issue. If/when this is changed, you can read it in the changelogs/releases.
